### ISSUE TITLE
Saat terlalu lama tidak aktif, baiknya logout bukan exception

### ISSUE THREAD

**Issue by pascalalfadian** [ftisunpar/IFStudentPortal#53]

**Comment by pascalalfadian** [comment]
Tim @kevintjoe, coba nanti di kelas kamu start IFStudentPortal di komputer masing2 (pull dulu ke versi terbaru), kemudian login, dan biarkan diam selama:
- 15 menit
- 30 menit
- 45 menit
- 60 menit

(coba di komputer berbeda-beda).

Kemudian nanti setelah waktu habis, akses halaman lain dan lihat apakah ada exception atau tidak. Nanti kita lihat sama-sama exception nya apa.

**Comment by kevintjoe** [comment]
Siap pak

Sent from Yahoo Mail on Android 

  On Thu, Apr 28, 2016 at 10:01, Pascalnotifications@github.com wrote:  
Tim @kevintjoe, coba nanti di kelas kamu start IFStudentPortal di komputer masing2 (pull dulu ke versi terbaru), kemudian login, dan biarkan diam selama:
- 15 menit
- 30 menit
- 45 menit
- 60 menit

(coba di komputer berbeda-beda).

Kemudian nanti setelah waktu habis, akses halaman lain dan lihat apakah ada exception atau tidak. Nanti kita lihat sama-sama exception nya apa.
