### ISSUE TITLE
Bug lulus salah satu dari Proif atau Prosi

### ISSUE THREAD

**Issue by michaeladrian39** [ftisunpar/IFStudentPortal#57]
Syarat kelulusan adalah lulus Proif atau lulus Prosi (lulus salah satu)

**Comment by pascalalfadian** [comment]
Thanks! Bisa kirimkan **screenshot halaman syarat kelulusan** dan **DPS (Daftar Perkembangan Studi) yang didapat dari Student Portal** melalui salah satu dari:

1. Comment dari issue ini dengan attachmentnya, atau
2. Email attachment ke pascal [at] unpar [titik] ac [titik] id, dan beritahu saya di comment issue ini.

**Comment by pascalalfadian** [comment]
@michaeladrian39 dicoba lagi donk.

**Comment by pascalalfadian** [comment]
Saya close karena tidak ada respon.
