### ISSUE TITLE
Mengetikkan Silabus

### ISSUE THREAD

**Issue by pascalalfadian** [ftisunpar/IFStudentPortal#8]
_Catatan: Kebutuhan umum di #1 juga harus dipenuhi_

`FRS_08_001` SIAModels harus diperbaharui sehingga berisi deskripsi setiap mata kuliah, yang didapat dari file `Silabus-IF-2016-01-11.zip`.

`FRS_08_002` Perbaikan Juklak FTIS UNPAR versi elektronik harus dilakukan dengan cara:
1. Fork repositori [https://github.com/pascalalfadian/SIAModels](https://github.com/pascalalfadian/SIAModels)
2. Membuat interface `HasPraktikum` dan `HasResponsi` pada package `id.ac.unpar.siamodels.matakuliah.interfaces` (kosong tanpa method apapun)
3. Mengisikan deskripsi setiap mata kuliah. Untuk setiap kelas pada package `id.ac.unpar.siamodels.matakuliah`, harus dibuat keterangan kelas berisi deskripsi dari mata kuliah terkait pada zip, dan tag `@author` berisi dosen pengajar dari kuliah tersebut (sesuai di dokumen).
4. Untuk mata kuliah yang memiliki praktikum, kelas mengimplementasikan interface `HasPraktikum`, dan untuk mata kuliah yang memiliki responsi, kelas mengimplementasikan `HasResponsi`.
5. Push ke repositori hasil fork
6. Memastikan tidak ada _compile error_ dan tidak mengubah isi kelas.
7. Melakukan pull request ke repositori utama (termasuk melakukan perbaikan sampai pull request diterima)
8. Melaporkan daftar mata kuliah yang ada di zip tetapi tidak ada pada `SIAModels`.

Tips: tidak ada perubahan pada proyek `IFStudentPortal`.

Tips: contoh implementasi seperti berikut.

``` java
/**
 * Mata kuliah ini memperkenalkan berbagai algoritma dan teknik-teknik
 * penyelesaian masalah komputasi seperti rekursif, sorting, teknik divide dan
 * conquer, serta exhaustive search. Selain itu, pada kuliah ini juga dikenalkan
 * berbagai struktur data yang dapat digunakan untuk mendukung penyelesaian
 * masalah komputasi seperti ADT List, Stack dan Queue. Baik algoritma maupun
 * struktur data yang dikenalkan harus dapat diimplementasikan dan digunakan
 * oleh mahasiswa untuk menyelesaikan masalah dengan menggunakan suatu bahasa
 * pemrograman berorientasi objek.
 * @author husnulhakim@unpar.ac.id
 */
@MataKuliah(kode = "AIF102", nama = "Algoritma dan Struktur Data", sks = 4)
public class AIF102 implements HasPrasyarat, Wajib, HasPraktikum {

    @Override
    public boolean checkPrasyarat(Mahasiswa mahasiswa, List<String> reasonsContainer) {
        boolean ok = true;
        if (!mahasiswa.hasLulusKuliah("AIF101") && !mahasiswa.hasLulusKuliah("AIF191")) {
            reasonsContainer.add("Tidak memenuhi prasyarat lulus AIF101 atau AIF191");
            ok = false;
        }
        if (!mahasiswa.hasTempuhKuliah("AIF103")) {
            reasonsContainer.add("Tidak memenuhi prasyarat tempuh AIF103");
            ok = false;
        }
        return ok;
    }

}
```

**Comment by johanesadriano** [comment]
Kekurangan file pada Silabus
1. Folder MKU silabusnya kosong
2. Silabus PBWL isinya ProIf
3. Pemodelan Formal tidak ada silabus
4. AJK 2 tidak ada di silabus
5. AJK 3 tidak memiliki prasyarat pada java dan silabus
6. Skripsi 1 dan Skripsi 2 tidak ada silabus
7. Probabilitas & Statistika tidak ada silabus
8. Etika Profesi tidak ada silabus
9. AIF 210 IMK tidak ada silabus
10. Topik khusus AIF 332 tidak ada silabus
11. AIF 344 Pemodelan simulasi tidak ada silabus
12. AIF 362 SAT tidak ada silabus 
13.  AIF 406 - AIF 468 tidak ada silabus tapi ada java
14. AIF 111 & 112 ProKom ada silabus tidak ada java

**Comment by pascalalfadian** [comment]
done
